name: deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      env: env
      with:
        host: ec2-65-1-65-157.ap-south-1.compute.amazonaws.com
        username: ubuntu
        PASSWORD: ${{ secrets.PASSWORD }}
        script: whoami