name: deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ec2-65-1-65-157.ap-south-1.compute.amazonaws.com
        username: ${{ secrets.USERNAME }}
        password: Azhar.258
        script: whoami
