name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: executing remote ssh commands using password
      uses: ./
      with:
        host: ec2-65-1-65-157.ap-south-1.compute.amazonaws.com
        username: ubuntu
        password: ${{ secrets.PASSWORD }}
        script: whoami