name: deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ec2-65-1-65-157.ap-south-1.compute.amazonaws.com
        username: ${{ secrets.USERNAME }}
        password: Azhar.258
        script: whoami
