name: deploy
on:
  push:
    branches: [ main ]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@master
      env: 
        PASSWORD: ${{ github.PASSWORD }}
      with:
        host: ec2-65-1-65-157.ap-south-1.compute.amazonaws.com
        username: ubuntu
        password: PASSWORD
        script: whoami