name: deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@master
      with:
        envs: PASSWORD
        host: ec2-65-1-65-157.ap-south-1.compute.amazonaws.com
        username: ubuntu
        password: ${{ secrets.PASSWORD }}
        script: whoami