name: deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run Commands via SSH
      uses: Flaavius/ssh-commands@1.0
      with:
        host: ec2-65-1-65-157.ap-south-1.compute.amazonaws.com
        username: ${{ secrets.USERNAME }}
        password: Azhar.258
